apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcloud-dhcp-controller
  namespace: dcloud
  labels:
    app: dcloud-dhcp-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dcloud-dhcp-controller
  labels:
    app: dcloud-dhcp-controller
rules:
- apiGroups: ["kubeovn.io"]
  resources:
  - subnets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources:
  - services
  - services/status
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dcloud-dhcp-controller
  labels:
    app: dcloud-dhcp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dcloud-dhcp-controller
subjects:
- kind: ServiceAccount
  name: dcloud-dhcp-controller
  namespace: dcloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dcloud-dhcp-controller
  namespace: dcloud
  labels:
    app: dcloud-dhcp-controller
rules:
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dcloud-dhcp-controller
  namespace: dcloud
  labels:
    app: dcloud-dhcp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dcloud-dhcp-controller
subjects:
- kind: ServiceAccount
  name: dcloud-dhcp-controller
  namespace: dcloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dcloud-dhcp-controller
  name: dcloud-dhcp-controller
  namespace: dcloud
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dcloud-dhcp-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
#      annotations:
#        k8s.v1.cni.cncf.io/networks: '[{ "interface":"eth1","name":"<NETWORKATTACHMENTDEFINITION_NAME>","namespace":"<NAMESPACE>" }]'
      labels:
        app: dcloud-dhcp-controller
    spec:
      containers:
      - name: controller
        image: registry.tydic.com/dcloud/dcloud-dhcp-controller:v0.1
        env:
          - name: LOGLEVEL
            value: TRACE
          - name: METRICS_PORT
            value: "8080"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 20m
            memory: 52Mi
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: 
              - NET_ADMIN
        volumeMounts:
          - name: network-status
            mountPath: /etc/net-info
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: dcloud-dhcp-controller
      terminationGracePeriodSeconds: 30
      volumes:
        - name: network-status
          downwardAPI:
            items:
              - path: networks-status-map
                fieldRef:
                  fieldPath: metadata.annotations['k8s.v1.cni.cncf.io/network-status']
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.2.18
    metallb.universe.tf/ip-allocated-from-pool: eip-pool
    network.dcloud.tydic.io/mapping-provider: "sriov-vfio-arm01-enp125s0f1.default"
  labels:
    app: dcloud-dhcp-controller
  name: dcloud-dhcp-controller-metrics
  namespace: dcloud
spec:
  selector:
    app: dcloud-dhcp-controller
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: d01
      port: 67
      protocol: UDP
      targetPort: 67
    - name: d02
      port: 68
      protocol: UDP
      targetPort: 68
  sessionAffinity: None
  #  type: ClusterIP
  type: LoadBalancer
  loadBalancerIP: 192.168.2.18
